[build]
    command = "cd netlify && cd functions && npm i"
    functions = "netlify/functions"
[dev]
  autoLaunch = false
[template.environment]
PAYPAL_CLIENT_ID= "Your PayPal API client ID"
PAYPAL_SECRET="Your PayPal API secret"