[build]
    command = "cd netlify && cd functions && npm i"
    functions = "netlify/functions"
    publish ="."
[dev]
  autoLaunch = false
[template.environment]
PAYPAL_CLIENT_ID= "Your PayPal Sandbox App's client ID"
PAYPAL_SECRET="Your PayPal Sandbox App's API Secret"